### ISSUE TITLE
Left aligned layout(?)

### ISSUE THREAD

**Issue by Sollace** [furbooru/philomena#3]
I can't find any option to turn off the centred layout mode. 🌵 

Has this feature been removed?

**Comment by Xe** [comment]
Yes, it has been removed in order to make it easier to develop new features for the site. Apparently it first existed as a result of it being pulled over from the first iteration of Derpibooru's [booru-on-rails](https://github.com/derpibooru/booru-on-rails), and it was pulled over into Philomena as a side effect of this. We don't really want to maintain two frontends to the site (it means 2x the testing for a setting that is _very easy_ to ignore on accident), so we removed that functionality. 

However, if you are comfortable with using userscripts, follow the instructions [here](https://furbooru.org/forums/meta/topics/welcome-to-furbooru-beta-information-about-the-site-as-a-work-in-progress?post_id=153#post_153). It would change this:

![2020-07-06-171803_1920x1061_scrot](https://user-images.githubusercontent.com/529003/86645869-c7778380-bfac-11ea-8b4c-12345b8f187c.png)

to this:

![2020-07-06-171849_1920x1061_scrot](https://user-images.githubusercontent.com/529003/86645886-cba3a100-bfac-11ea-997e-b250e357588b.png)

I'm sorry we can't bring back the option in the settings, but we are doing this to make it easier for us to make the booru even better.

**Comment by Sollace** [comment]
That's unfortunate... A simple alignment change shouldn't have required an entirely different front-end layer.

It's fine. I'll manage with the centred layout as it is. I may end up not using this site all that much anyway. It's just nice having options other than derpi.
